// <auto-generated />
using FeatureFlagEngine.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FeatureFlagEngine.Infrastructure.Migrations
{
    [DbContext(typeof(FeatureFlagDbContext))]
    [Migration("20260220235946_AddRegionOverrides")]
    partial class AddRegionOverrides
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("FeatureFlagEngine.Core.Models.FeatureFlag", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.HasKey("Name");

                    b.ToTable("FeatureFlags");
                });

            modelBuilder.Entity("FeatureFlagEngine.Core.Models.GroupOverride", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FeatureFlagName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FeatureFlagName", "GroupId")
                        .IsUnique();

                    b.ToTable("GroupOverrides");
                });

            modelBuilder.Entity("FeatureFlagEngine.Core.Models.RegionOverride", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FeatureFlagName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RegionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FeatureFlagName", "RegionId")
                        .IsUnique();

                    b.ToTable("RegionOverrides");
                });

            modelBuilder.Entity("FeatureFlagEngine.Core.Models.UserOverride", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FeatureFlagName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FeatureFlagName", "UserId")
                        .IsUnique();

                    b.ToTable("UserOverrides");
                });

            modelBuilder.Entity("FeatureFlagEngine.Core.Models.GroupOverride", b =>
                {
                    b.HasOne("FeatureFlagEngine.Core.Models.FeatureFlag", null)
                        .WithMany("GroupOverrides")
                        .HasForeignKey("FeatureFlagName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FeatureFlagEngine.Core.Models.RegionOverride", b =>
                {
                    b.HasOne("FeatureFlagEngine.Core.Models.FeatureFlag", null)
                        .WithMany("RegionOverrides")
                        .HasForeignKey("FeatureFlagName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FeatureFlagEngine.Core.Models.UserOverride", b =>
                {
                    b.HasOne("FeatureFlagEngine.Core.Models.FeatureFlag", null)
                        .WithMany("UserOverrides")
                        .HasForeignKey("FeatureFlagName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FeatureFlagEngine.Core.Models.FeatureFlag", b =>
                {
                    b.Navigation("GroupOverrides");

                    b.Navigation("RegionOverrides");

                    b.Navigation("UserOverrides");
                });
#pragma warning restore 612, 618
        }
    }
}
